spring:
  application:
    name: scw-project
  datasource:
    url: jdbc:mysql://192.168.249.128/atcrowdfundings
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.249.128
    port: 6379
#配置上传文件的大小限制
#文件大小 MB必须大写
#maxFileSize 是单个文件大小
#maxRequestSize是设置总上传的数据大小
  #servlet: 
  # multipart:
    # enabled: true
     #max-file-size: 20MB
     #max-request-size: 30MB
server:
  port: 8000
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true # 支持注册中心使用ip-address
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    